### ISSUE TITLE
Saas-help-2

### ISSUE THREAD

**Issue by emfeather94** [emfeather94/saas-website#3]
Hi Christina -

A couple questions:

1) markbot is telling me I have a parse error on line 174 of my main.css. I thought I had fixed it but it still says it is wrong - can you look over?

2) I tried adding the "scrollable" element to my table, as it keeps getting squished at smaller screen sizes, not sure what I am missing.

3) markbot has my index navigation marked off green for button hover, but also says that it is not functioning properly (as far as I am aware it is) - again, could you look over?

Thank you!

@muxlowc

**Comment by muxlowc** [comment]
@emfeather94 

1) yah there is definitely not a parse error i can see..hah

2) You need to tell your table to have a minimum width so that the scrolling aspect activates. Also, switch around where you have your table-wrapper and scrollable class:

```
      <div class="island table-wrapper scrollable">
        <table class="push-0">
```

.table-wrapper table {
  min-width: 45em;
}

3) I also don't see a problem here - you can just ignore that one too 

Also, make sure you add type="submit" to your button on your sign-up page, and also make sure you add in some skip-links with corresponding Id's if you can :)

**Comment by emfeather94** [comment]
@muxlowc 

thank you so much!
